version: '3.4'

services:
  app:
    image: ${DOCKER_REGISTRY-}app
    build:
      context: .
      dockerfile: App/Dockerfile
  app.database:
    image: ${DOCKER_REGISTRY-}appdatabase
    build:
      context: .
      dockerfile: App.Database/Dockerfile
